run:
  timeout: 10m
  go: "1.20"
  skip-files:
    - "zz_generated.*\\.go$"
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - containedctx
  - depguard
  - dogsled
  - dupword
  - durationcheck
  - errcheck
  - errchkjson
  - exportloopref
  - ginkgolinter
  - goconst
  - gocritic
  - godot
  - gofmt
  - goimports
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - importas
  - ineffassign
  - misspell
  - nakedret
  - nilerr
  - noctx
  - nolintlint
  - nosprintfhostport
  - prealloc
  - predeclared
  - revive
  - rowserrcheck
  - staticcheck
  - stylecheck
  - typecheck
  - unconvert
  - unused
  - usestdlibvars
  - whitespace
  # Disabled for now, but will be enabled as soon as possible
  # - unparam

linters-settings:
  ginkgolinter:
    # Suppress the wrong length assertion warning.
    suppress-len-assertion: false
    # Suppress the wrong nil assertion warning.
    suppress-nil-assertion: false
    # Suppress the wrong error assertion warning.
    suppress-err-assertion: true
  stylecheck:
    checks: ["all", "-ST1000", "-ST1020"]
  importas:
    no-unaliased: true
    alias:
      # Kubernetes
      - pkg: k8s.io/api/core/v1
        alias: corev1
      - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
        alias: apiextensionsv1
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
      - pkg: k8s.io/apimachinery/pkg/api/errors
        alias: apierrors
      - pkg: k8s.io/apimachinery/pkg/util/errors
        alias: kerrors
      - pkg: k8s.io/api/apps/v1
        alias: appsv1
      - pkg: k8s.io/api/batch/v1
        alias: batchv1
      - pkg: k8s.io/api/core/v1
        alias: corev1
      - pkg: k8s.io/api/networking/v1
        alias: networkingv1
      # Cert Manager
      - pkg: github.com/cert-manager/cert-manager/pkg/apis/certmanager/v1
        alias: certmanagerv1
      # Prometheus Operator
      - pkg: github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1
        alias: monitoringv1
      # Istio
      - pkg: istio.io/client-go/pkg/apis/networking/v1beta1
        alias: istionetworkingv1beta1
      - pkg: istio.io/client-go/pkg/apis/security/v1beta1
        alias: istiosecurityv1beta1
      - pkg: istio.io/api/security/v1beta1
        alias: istioapisecurityv1beta1
      - pkg: istio.io/api/type/v1beta1
        alias: istioapiv1beta1
      # Controller Runtime
      - pkg: sigs.k8s.io/controller-runtime
        alias: ctrl
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-specific: true
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
      - name: redefines-builtin-id
      - name: bool-literal-in-expr
      - name: constant-logical-expr
      # Disabled for now, but will be enabled as soon as possible
      # - name: exported
      # - name: package-comments
      # - name: unused-parameter
issues:
  max-same-issues: 0
  max-issues-per-linter: 0