name: Tests and build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

env:
  GO_VERSION: "1.20.3"
  GOLANG_CI_VERSION: v1.52.2

jobs:
  license:
    name: Check license on files
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - name: check
        run: make check-license
  lint:
    name: Lint files
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANG_CI_VERSION }}
  test:
    name: Test packages
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
      - name: build
        run: make test